// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaS9eujBHEvyXw9X25wnzjXvlHGeEcPFU',
    appId: '1:432371963345:web:d3451d00e5e5f556aa7cf0',
    messagingSenderId: '432371963345',
    projectId: 'nbsstorage-ba8de',
    authDomain: 'nbsstorage-ba8de.firebaseapp.com',
    storageBucket: 'nbsstorage-ba8de.appspot.com',
    measurementId: 'G-1DRT4Q36NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMxrYGdkXZbWTV0oN7CRHLcJSOtnKAlUc',
    appId: '1:432371963345:android:d8a8421551e5ae39aa7cf0',
    messagingSenderId: '432371963345',
    projectId: 'nbsstorage-ba8de',
    storageBucket: 'nbsstorage-ba8de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYc816mdDTzi0jvHA_bblxxfzQ2sTe-N4',
    appId: '1:432371963345:ios:1decb28988cf4c4faa7cf0',
    messagingSenderId: '432371963345',
    projectId: 'nbsstorage-ba8de',
    storageBucket: 'nbsstorage-ba8de.appspot.com',
    iosBundleId: 'com.example.projectPayrollNextbpo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYc816mdDTzi0jvHA_bblxxfzQ2sTe-N4',
    appId: '1:432371963345:ios:8e356f36b6b600c3aa7cf0',
    messagingSenderId: '432371963345',
    projectId: 'nbsstorage-ba8de',
    storageBucket: 'nbsstorage-ba8de.appspot.com',
    iosBundleId: 'com.example.projectPayrollNextbpo.RunnerTests',
  );
}
